Enable lv_binding_micropython as USER_C_MODULE
lvgl/lv_binding_micropython pull request #341
Opened 2024-05-13 17:30 UTC by Carglglz

This is an updated version of #242 which allows to build `lv_binding_micropython` as a `USER_C_MODULE` with latest upstream MicroPython.

Tested on :  
- unix port (linux, macOS) 
- esp32  

This also adds a basic test that can be run with MicroPython test suite. e.g. 
```bash
$ ./run-tests.py ../../user_modules/lv_binding_micropython/tests/basic/basic.py
pass  ../../user_modules/lv_binding_micropython/tests/basic/basic.py
1 tests performed (34 individual testcases)
1 tests passed
```

2024-05-14 05:18 UTC, PGNetHun commented
Thank you, I will test it, too!

2024-05-19 22:20 UTC, Carglglz commented
@MathyV I've just updated the tests, you should be able to run `tests/display` with your driver (I've already tested it and it works but I have no physical display to get visual feedback )

2024-05-21 04:02 UTC, kdschlosser commented
I am confused as to the purpose of this PR. The purpose of a user c module should be to keep the binding code self contained where modifications to the micropython build system would not need to be made to get it to compile.

2024-05-21 16:22 UTC, Carglglz commented
> The purpose of a user c module should be to keep the binding code self contained where modifications to the micropython build system would not need to be made to get it to compile.

Which it is exactly this, the tests are not necessary just convenient, if necessary I can split this PR.

> where modifications to the micropython build system would not need to be made to get it to compile.

I am confused too, where do you see these modifications? 👀

2024-05-21 19:55 UTC, kdschlosser commented
There is no PR in https://github.com/lvgl/lv_micropython that removes all of the code that has been added to the build system to compile LVGL into micropython. I am making an assumption about that repo still being used because I am not seeing any kind of a connection between this repo and micropython anywhere that would indicate something different.

I am also failing to see how this is able to be compiled as a user c module as there is no micropython.cmake or micropython.mk which is what is used to compile it as a user_c_module. The cmake file is not as important but the makfile must be named as micropython.mk in order for the micropython build system to locate it due to a directory and not a file needing to be provided in a make build.

2024-05-21 19:56 UTC, kdschlosser commented
I am trying to figure out how I would use this as a user_c_module. What to I point micropython to?

2024-05-21 21:06 UTC, Carglglz commented
> There is no PR in https://github.com/lvgl/lv_micropython that removes all of the code that has been added to the build system to compile LVGL into micropython. I am making an assumption about that repo still being used because I am not seeing any kind of a connection between this repo and micropython anywhere that would indicate something different.

No, this is independent of `lv_micropython`,  with this PR anyone can build `lv_binding_micropython` as a USER_C_MODULE from upstream MicroPython.

> I am also failing to see how this is able to be compiled as a user c module as there is no micropython.cmake or micropython.mk which is what is used to compile it as a user_c_module

Not sure where you are looking at 😕 they are here
<img width="634" alt="Screenshot-PR-341" src="https://github.com/lvgl/lv_binding_micropython/assets/15161684/1ec07288-3fed-41ef-bbcd-7bfa6b199adf">

> I am trying to figure out how I would use this as a user_c_module. What to I point micropython to?

Just create a directory next to MicroPython repo e.g. named `user_modules`, then clone `lv_binding_micropython` inside. 

To built unix port just do 

```
micropython/ports/unix$ : make USER_C_MODULES=../../../user_modules
```  


In my case I compile my own unix variant for convenience (**not necessary**)

```
 make VARIANT_DIR=$MY_VARIANTS/UNIX_DEV -j4
```
`UNIX_DEV` is just a copy of `variants/standard` but with:

this added to `manifest.py`

```
include("$(MPY_DIR)/../user_modules/lv_binding_micropython/ports/unix")
```

this added to `mpconfigvariant.h`

```
// Required for LVGL
#define MICROPY_ENABLE_SCHEDULER       (1)
#define MICROPY_MODULE_BUILTIN_INIT    (1)
#define MICROPY_PY_SYS_SETTRACE        (0)
```
And this added to `mpconfigvariant.mk`

```
FROZEN_MANIFEST ?= $(VARIANT_DIR)/manifest.py
USER_C_MODULES ?= ../../../user_modules
```

In any case `lv_micropython` could be updated to add custom variants but again I don't think it is necessary.

2024-05-21 22:52 UTC, kdschlosser commented
OK so say I clone this repo in my IDE's project folder. Then I clone micropython 1.23 into the binding cloned folder. To build it I would have to use the following command to build

`make -c micropython/ports/unix USER_C_MODULES="../../../../"`

When I do that make is going to search every single one of my other projects in a recursive manner and look for micropython.mk files. It is going to also do this for the directory the binding repo has been cloned into and if it finds any micropython.mk files anywhere it is going to compile those as user c modules as well. 


If this PR is accepted when the lv_micropython repo gets updated I am guessing it is going to break due to the gen_mpy script being altered to work with micropython 1.23.

How were you able to handle the build with the ESP32s driver reliance on the esp-idf and that version needing to be 4.4 where as micropython 1.23 uses 5.1.x or 5.2.x I don't remember which. Support for 4.4 was removed in micropyton 1.21 I believe, it may have been 1.20...

compiling LVGL as a user c module was never the issue, it was compiling the rest of the things that go along with it. How dows one go about setting up the display drivers?

I am thinking that you may have missed this...

https://github.com/lvgl/lv_binding_micropython/tree/65d882d1c9958c4842d577741c7e70556282576f/driver/esp32

everything in the drivers folder also needs to be handled as well. The .py files need to be frozen into the firmware and I am not seeing where that is done.

2024-05-21 23:45 UTC, Carglglz commented
>OK so say I clone this repo in my IDE's project folder. Then I clone micropython 1.23 into the binding cloned folder. To build it I would have to use the following command to build 
`make -c micropython/ports/unix USER_C_MODULES="../../../../"`
When I do that make is going to search every single one of my other projects in a recursive manner and look for micropython.mk files. It is going to also do this for the directory the binding repo has been cloned into and if it finds any micropython.mk files anywhere it is going to compile those as user c modules as well.

No this is what I meant 
```
my_ide_project: $ tree
.
├── micropython 
 ...
└──  user_modules
       └── lv_binding_micropython 
```

> If this PR is accepted when the lv_micropython repo gets updated I am guessing it is going to break due to the gen_mpy script being altered to work with micropython 1.23.

The check passed which seems to build `lv_micropython` with the contents of this PR 

> the gen_mpy script being altered to work with micropython 1.23

Again those changes should be backwards compatible as the check confirms...

> compiling LVGL as a user c module was never the issue, it was compiling the rest of the things that go along with it. 

Yes it was, `bindings.cmake` only works with rp2 port

> How dows one go about setting up the display drivers?

The display drivers are a nice thing to have but not necessary to build `lvgl` as a `USER_C_MODULE`. 

>  How were you able to handle the build with the ESP32s driver reliance on the esp-idf and that version needing to be 4.4 where as micropython 1.23 uses 5.1.x or 5.2.x I don't remember which. Support for 4.4 was removed in micropyton 1.21 I believe, it may have been 1.20...

> I am thinking that you may have missed this...

> https://github.com/lvgl/lv_binding_micropython/tree/65d882d1c9958c4842d577741c7e70556282576f/driver/esp32

> everything in the drivers folder also needs to be handled as well. The .py files need to be frozen into the firmware and I am not seeing where that is done.

I'm aware of this, see my comments https://github.com/lvgl/lv_binding_micropython/pull/242#issuecomment-2087739448 and 
https://github.com/lvgl/lv_binding_micropython/pull/242#issuecomment-2103572023

2024-07-28 08:26 UTC, chieve-bale commented
is there possible to create new repositories under lvgl org. lv_micropython is real confuseing with micropython version and idf version. there is saying in README.md lv_micropython as a example to show how to bind lv_binding_micropython,but when i try to figure out how to bind as a submodule under official micropython repo, it is real not  friendly and easy to achieve.
so for freshman like me, make lv_bind_micropython as a independent user c module is real esay to achieve. there is a good example repo in my consideration:
https://github.com/devbis/st7789_mpy.git
or
https://github.com/russhughes/st7789_mpy.git
i know this may let lv_micropython work error, so i advise to create new repo。it may let the code maintenance more easy( i guess)

sorry about my terrible english explanation, it is not my first language.

2024-08-09 22:59 UTC, TheBestJohn commented
Just popping in to say this is great work. I just got this successfully running on a LILYGO T_Display using the latest Micropython. 
I copied the utils and Stdriver to my freeze directory and I had to modify my partition file as it seems to make the micropython.bin quite a bit beefier.

I haven't done too much with it yet as I'm still learning the ropes of this library but I did get me a press me button on a display with no touch inputs. There was some initial issues with the uasyncio stuff but I haven't looked too closely into that as it may be an error I made with the partitions.

2024-08-11 12:51 UTC, Carglglz commented
@TheBestJohn 
Thanks for testing this!!

> EDIT: The crashing seems to happen when I re-upload my script. Not sure the proper teardown of lvgl yet but it doesn't seem to be due to this C modulization but instead something to do with the co-processor or something

This may be related to #343 , not sure how are you uploading the script (probably there is a soft reset involved?) but you need to do a hard reset or call `lvgl.deinit()` before the soft reset (at least for the LVGL side). Respect to the driver yo may need to deinit SPI too (although this may not work see again #343, but that would be on the MicroPython side)

The are some [tests](https://github.com/Carglglz/lv_binding_micropython/tree/mpy-tests/tests) that you may want to run with
```
$  ./run-tests.py ../../user_modules/lv_binding_micropython/tests/api/*.py --target esp32 --device /dev/tty.<ID>
```

>  haven't done too much with it yet as I'm still learning the ropes of this library but I did get me a press me button on a display with no touch inputs.

For touch inputs you need to register an "input device" have a look at [`testdisplay.py`](https://github.com/Carglglz/lv_binding_micropython/blob/mpy-tests/tests/testdisplay.py) and [indev docs](https://docs.lvgl.io/master/porting/indev.html). Then `lvgl.task_handler()` needs to be called to be able to process events, see [`lib/lv_utils.py`](https://github.com/Carglglz/lv_binding_micropython/blob/mpy-tests/lib/lv_utils.py), which can be done using a timer or as an asyncio task, i.e the asyncio event loop must be running.

2025-01-22 07:13 UTC, solosky commented
I have built on esp-idf v5.2.2 successfully, but it seems the espidf.c is not complied as python module, just do some trouble shooting, it seems espidf.c is commented in mkrules_usermod.cmake. if uncommented, the project even cannot compile. 
I am still struggling to make it complied..

2025-01-23 01:52 UTC, Carglglz commented
@solosky 
> but it seems the espidf.c is not complied as python module, just do some trouble shooting, it seems espidf.c is commented in mkrules_usermod.cmake

yes, currently `espidf.c` targets ESP-IDF v4.x, so to make it compiled you will need to update it to be compatible with ESP-IDF v5.x first.

 > I have built on esp-idf v5.2.2 successfully

Yes, and lvgl should work, `espidf.c` is only required for the display drivers. As an alternative you may be able to find drivers for your display here:

- https://github.com/MathyV/lvgl_esp32_mpy 
- https://github.com/PyDevices/pydisplay
- https://github.com/lvgl-micropython/lvgl_micropython

2025-02-10 23:14 UTC, PGNetHun commented
Hello!
Thanks for the changes, but these PR changes (and whatever extra code you need) should be in a **separate repository**, for example: `lv_micropython_user_module`,

-> Because this binding repo and your changes are 2 different approaches:
- `lv_binding_micropython` is kind of "direct integration" into MicroPython code
- your PR generates 'binding' as MicroPython user C module

Please do not mix the 2 approaches in the same repository, use a separate one for your USER_C_MODULE approach (like @kdschlosser created separated repo).

I try to update `lv_micropython` repo with latest MicroPython release version 1.24.1 (update from upstream), but it takes time to stabilize and test it.

2025-02-10 23:15 UTC, PGNetHun requested changes
PR changes should go to separate repo, as it uses different approach than `lv_binding_micropython`.

2025-02-11 03:12 UTC, Carglglz commented
Hi @PGNetHun, this PR doesn't change the original approach of "direct integration" into MicroPython codebase (wrong approach IMO, but that's another discussion) the changes you see are:

- Necessary fixes: https://github.com/lvgl/lv_binding_micropython/pull/341/commits/6a5eb8810d76730097b760f1036e8218ee0ae3a5, https://github.com/lvgl/lv_binding_micropython/pull/341/commits/4ff1ea980b12f05a159b857c1ecfddb6f0ea3b3c, https://github.com/lvgl/lv_binding_micropython/pull/341/commits/c0eecf6e9918b2a23b973564a158ad98b159bd29, https://github.com/lvgl/lv_binding_micropython/pull/341/commits/f76c25fbc5a19071ebc693c3d03b8aa04a5296bd, https://github.com/lvgl/lv_binding_micropython/pull/341/commits/f47c1fa504515f959777b075097f558d212bb82c, https://github.com/lvgl/lv_binding_micropython/pull/341/commits/b51bf02972c80f3c833ae522a432ab09667d0b99

These are to update to latest MicroPython + LVGL and also some bug fixes.

- To enable `lv_binding_micropython` as `USER_C_MODULE`: https://github.com/lvgl/lv_binding_micropython/pull/341/commits/d7ffcf6f08e938039f006ede75790e6e5595ce2b, https://github.com/lvgl/lv_binding_micropython/pull/341/commits/6fae7e750fcc5d2bcfd14070facfec2b38bda5dd

Again, these doesn't change the original approach, it just enables the `USER_C_MODULE` approach that's already used in Raspberry Pi Pico port for the rest of the ports. (see https://github.com/lvgl/lv_micropython?tab=readme-ov-file#raspberry-pi-pico-port)

- Optional "and whatever extra code you need": https://github.com/lvgl/lv_binding_micropython/pull/341/commits/53f858c3d13ba0201340f812fc9cded7dd672628, https://github.com/lvgl/lv_binding_micropython/pull/341/commits/12955be6b0a58bdc95d32ed0d8ce202e7bdf5459, https://github.com/lvgl/lv_binding_micropython/pull/341/commits/a6fffeaaf17899375574617d312ec049d872e9f3

The tests I added aren't necessary, just convenient. 

> I try to update lv_micropython repo with latest MicroPython release version 1.24.1 (update from upstream), but it takes time to stabilize and test it.

Yes it takes time if you follow the "wrong" approach, the only thing I can see it could take time is this 

>  currently espidf.c targets ESP-IDF v4.x, so to make it compiled you will need to update it to be compatible with ESP-IDF v5.x first.

Everything else is already working. 

What I think it needs to be done to update `lv_micropython` and take a more sustainable approach:

- [ ]  Create a branch and checkout MicroPython release version 1.24.1

- [ ] Create a `user_modules` directory in top directory, add `lv_binding_micropython` as a submodule and checkout this PR or @andrewleech's https://github.com/lvgl/lv_binding_micropython/pull/242

- [ ] Add  `unix-lvgl` `VARIANT` and other `BOARD` variants for each port, and add `USER_C_MODULES` flag in ` mpconfigvariant.mk` or ` mpconfigboard.cmake`/ `mpconfigboard.mk`.

This is IMO way easier to maintain in the long run than current approach. 

Let me know if I can help with any of these changes 👍🏼

2025-02-11 09:53 UTC, andrewleech commented
@Carglglz I've been putting significant efforts into my original PR https://github.com/lvgl/lv_binding_micropython/pull/242 lately as we're using this at work with a mimx board.

I've included your changes from here now as well, you've made many solid improvements and fixes! 

I do believe however that the broad code reformatting in this PR makes it very hard to see the functional changes made; while cherry picking your commits in my PR I've avoided the reformatting so it should be easier for others to review.

While I support cleaning up formatting in principle, I believe it should be done in a separate PR and carefully considered as it means merging any other existing PR's afterwards is significantly more difficult.

@PGNetHun the charges made in these two PR's are such that, when combined with improvements in newer micropython versions, there no longer needs to be a customised fork of micropython at all. This bindings repo can be used with official micropython instead, meaning no extra maintenance is needed at all. 

The user C module approach is the officially supported way to extend micropython with separate C libraries.

I'm a regular contributor to micropython and have spoken to the core team; there is interest in potentially including lvgl as an official library in the micropython codebase such that board profiles could be preconfigured to include lvgl. That's a longer term goal though that's built in top of this repo and updating it to work as a standard user C module.

FWIW I consider my PR basically ready for review, it's tested and working with mimx and esp32 ports, I just need to test with rp2 to ensure that still works. 

I am planning on putting together another separate repo as an example / pattern to follow to show how this binding repo can be used with official micropython as a user C module, included as a submodule outside of the micropython tree. That might make it clearer to see how these changes are intended to work.

2025-03-15 13:44 UTC, PGNetHun commented
@Carglglz 
Thank you for your help transforming binding into MicroPython user module.

Changes are merged to main branch: 
- `lv_binding_micropython`: https://github.com/lvgl/lv_binding_micropython/pull/368
- `lv_micropython`: https://github.com/lvgl/lv_micropython/pull/89

Please verify that it's OK, and if yes, please close this PR.

2025-03-17 21:39 UTC, Carglglz commented
@PGNetHun , thank you for reviewing this and I'm glad that you followed my advice. 
I've just rebased, tested and it works as expected 👍🏼, I will comment about CI failing in #368.

2025-03-17 21:39 UTC, closed without merging

2025-03-17 22:21 UTC, PGNetHun commented
Although there are still some open issues, but at least `lv_micropython` is updated with latest MicroPython code.

The issues still open:
1. Some CI build fail (github workflows in LVGL repo)
2. ESP32 -> ILI9xxx not working: `espidf.c` is not compiled into `lv_micropython`, so ESP32 ILI9xxx driver module is not freezed into firmware. I intend to replace this with LVGL built-in MIPI drivers: https://docs.lvgl.io/master/details/integration/driver/display/gen_mipi.html

Advantage of MIPI display drivers:
- maintained inside LVGL repo: https://github.com/lvgl/lvgl/tree/master/src/drivers/display
- fully written in C language -> no switching between C and MicroPython like in ILI9xxx
- generic API interface, and platform-independent high-level display control
- I2C / SPI communication can be implemented platform-dependent, for example ESP32 can initiate buffer in DMA-able memory space, and use hardware SPI module to send pixel data in DMA
- supported displays at the moment: ST7789, ST7735, ST7796, ILI9341
- simple to add new displays following MIPI pattern

The only disadvantage what I see now is that we have to implement the MicroPython C module wrapper for MIPI drivers.
I've started this also, but `mpy_gen.py` has a bug generating the MIPI callback wrappers.

2025-03-19 09:13 UTC, andrewleech commented
I've been working on a compatible display driver for mimx1170 that's build / integrated as a separate user C module alongside the lvgl user C module: https://github.com/andrewleech/imxrt1170_display_driver

I also want to look more closely at the drivers included in https://github.com/PyDevices/pydisplay I know a lot of very comprehensive work has gone into these already, but not sure how easily they fit / integrate into this lvgl structure.

I'm also very interested in being able to use the display drivers included in lvgl, but as you say they currently need to be integrated at a C level. 

I've previously discussed adding internal APIs to micropython to support background / non-blocking use of peripherals like SPI and i2c for applications like this (https://github.com/orgs/micropython/discussions/13081)
This did result in a general consensus of a basic API and mechanism to work towards but I haven't had time to start implementing it.

I haven't actually looked at these newer lvgl built in drivers to see how they're integrated in practice, so don't know how best to include / use them with micropython.

2025-03-30 01:50 UTC, Carglglz commented
@PGNetHun this may be interesting for `esp-idf` drivers, https://github.com/esp-arduino-libs/ESP32_Display_Panel, seems to be updated with MicroPython support, maybe this could be added as a submodule and integrated with the MIPI driver 👍🏼

2026-01-31 21:44 UTC, StephenDone commented
@PGNetHun @andrewleech,
This move to using user c modules looks like a great step forward.
I am a newbie to building micropython and also a newbie to lvgl. My attempts to build have been thwarted at every turn by out of date documentation. Clearly many hundreds of hours have been spent producing this excellent update. But could someone please spend 5 minutes updating readme.md to match. Just take a look at what it currently says...

### Adding MicroPython Bindings to a project
An example project of "MicroPython + lvgl + Bindings" is [lv_mpy](https://github.com/lvgl/lv_mpy). Here is a procedure for adding lvgl to an existing MicroPython project. (The examples in this list are taken from [lv_mpy](https://github.com/lvgl/lv_mpy)):

- Add [lv_bindings](https://github.com/lvgl/lv_binding_micropython) as a sub-module under lib.
- Add lv_conf.h in lib
- Edit the Makefile to run gen_mpy.py and build its product automatically. Here is [an example](https://github.com/lvgl/lv_micropython/blob/2940838bf6d4999050efecb29a4152ab5796d5b3/py/py.mk#L22-L38).
- Register lvgl module and display/input drivers in MicroPython as a builtin module. [An example](https://github.com/lvgl/lv_micropython/blob/2940838bf6d4999050efecb29a4152ab5796d5b3/ports/unix/mpconfigport.h#L230).
- Add lvgl roots to gc roots. [An example](https://github.com/lvgl/lv_micropython/blob/2940838bf6d4999050efecb29a4152ab5796d5b3/ports/unix/mpconfigport.h#L317-L318).
- Configure lvgl to use Garbage Collection by setting several LV_MEM_CUSTOM_* and LV_GC_* macros [example](https://github.com/lvgl/lv_mpy/blob/bc635700e4186f39763e5edee73660fbe1a27cd4/lib/lv_conf.h#L28) lv_conf.h was moved to lv_binding_micropython git module.
- Make sure you configure partitions correctly in partitions.csv and leave enough room for the LVGL module.
- Something I forgot? Please let me know.

As far as I can tell, none of the above is now correct and just produces build errors. There are people raising issues because they are encountering build errors... because they are following the instructions... which are wrong! https://github.com/lvgl/lv_binding_micropython/issues/400 - nobody helped this guy and he posted in November.

The only reason that I am trying to build micropython with lvgl (my own equivalent of lv_micropython) is because I want to use it with a Raspberry Pi Pico 2W which was released in November 2024. But lv_micropython is so old that it does not include it. I now have a working build of 1.24.1. Hopefully I can find a combo of micropython and lvgl that will give me 1.25 or higher, but the matching tags and branches I've found run out at 1.24.1. I think that lv_micropython should be binned/deprecated etc. Then a new 'model' repo created that has the latest release micropython and matching lvgl bindings in it. That way, a newbie who needs to compile a firmware can just checkout the repo and get started. The build instructions will then be exactly as for micropython, but with the addition of the user c modules parameters in the build.

This is what I ended up doing...

```
git clone https://github.com/micropython/micropython.git
git fetch --tags
git tag
git checkout tags/v1.24.1

mkdir user_modules
cd user_modules
git submodule add -b update/micropython_v1.24.1 https://github.com/lvgl/lv_binding_micropython.git ./lv_binding_micropython
cd ..

git submodule update --init --recursive user_modules/lv_binding_micropython
make -C ports/rp2 BOARD=RPI_PICO clean
make -C ports/rp2 BOARD=RPI_PICO submodules
make -j -C mpy-cross
make -j -C ports/rp2 BOARD=RPI_PICO USER_C_MODULES=../../user_modules/lv_binding_micropython/bindings.cmake
```

I realise this is a closed issue. If you would like me to create a feature request issue, just let me know.

Stephen Done

2026-02-01 23:40 UTC, andrewleech commented
@StephenDone thanks for bringing this up and yes - a clear example project has been on my personal backlog ever since I pushed the first version of this PR.... unfortunately my personal backlog if long and not very linear.

The gaps in _documentation_ are arguably a bigger issue than the lack of a simple example project, I agree this should be addressed. I actually think it would be quite valuable to copy your comment into a new issue to track separately - focussing on firstly getting the readme/docs aligned with the current project architecture and secondly getting some useful project examples set up to demonstrate.

2026-02-02 14:45 UTC, StephenDone commented
Hi @andrewleech,
Thanks for taking the time to reply. I see your name all over this repo, so I imagine you are a very busy man!

I reread my post, as you referred to 'examples' being needed. I guess you are referring to the 'model repository' I suggested. I was suggesting a repository that can be cloned by anyone wishing to build MP with LVGL on their own system. So basically a clone of MP combined with a compatible LVGL. There could be tagged versions of the repo so you could (for example), clone the repo for LVGL & MP 1.24.1. I guess this was the original intention of the lv_micropython repo, though this is now out of date, and looks rather tricky to update, given it's both 768 commits ahead and 1696 commits behind MP. I am suggesting that this new repo would replace lv_micropython, be much easier to maintain and get new users up and running with working LVGL / MP versions.

I have some experience in Windows, Delphi, MSBUILD, TeamCity, RTOS reverse engineering and various other stuff which has precisely zero overlap with any of the skills required to build LVGL and MP!!! What I am saying is that I am probably quite a suitable 'crash test dummy' for any documentation updates :-)

I can provide a list of hurdles that I have had to overcome in order to get a working build - a kind of 'customer journey of a muppet', if you like :-)

Let me know if and how I can help.